export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const REMOVE = 'REMOVE';
export const CREATE_REVIEW = 'CREATE_REVIEW';
export const CREATE_USER = 'CREATE_USER';
export const INSERT_REVIEW_INTO_RESTAURANTS = 'INSERT_REVIEW_INTO_RESTAURANTS';
