export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const REMOVE = 'REMOVE';
export const SET_ACTIVE_RESTAURANT_ID = 'SET_ACTIVE_RESTAURANT_ID';
export const CREATE_NEW_REVIEW = 'CREATE_NEW_REVIEW';
export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_USER = 'ADD_USER';
export const ADD_REVIEW_TO_RESTAURANT = 'ADD_REVIEW_TO_RESTAURANT';
